---
- name: Deploy Calculator Container
  hosts: local
  become: yes

  tasks:

    - name: Pull latest image
      command: docker pull prins05688/calculator:latest


    - name: Stop old container
      command: docker stop calculator-container
      ignore_errors: yes

    - name: Remove old container
      command: docker rm calculator-container
      ignore_errors: yes

    - name: Run new container
      command: docker run -dit --name calculator-container --restart unless-stopped prins05688/calculator:latest
