---
- name: Deploy Calculator Container
  hosts: local
  become: yes

  tasks:

    - name: Pull latest image
      command: docker pull prins05688/calculator:latest

    - name: Stop old container
      command: docker stop calculator-container
      ignore_errors: yes

    - name: Remove old container
      command: docker rm calculator-container
      ignore_errors: yes

    - name: Run new container
      command: docker run -d --name calculator-container prins05688/calculator:latest add 10 5
